
CREATE TABLE IF NOT EXISTS DBO.TRACKEE (
    TRACKEE_SID INT NOT NULL DEFAULT DBO.TRACKEE_SID.NEXTVAL, 
    TYPE VARCHAR, 
    NAME VARCHAR, 
    NOTES VARCHAR, 

    FREQUENCY_NUM INT, 
    FREQUENCY_UNIT VARCHAR, 
    ACTIVE_FLAG BOOLEAN,

    RECORD_CREATED_DT TIMESTAMP_NTZ(9),
    RECORD_UPDATED_DT TIMESTAMP_NTZ(9)
)
;