CREATE TABLE IF NOT EXISTS DWH.BUSINESS (

    BUSINESS_ID NUMBER(38,0) NOT NULL DEFAULT DWH.BUSINESS_ID_SEQ.NEXTVAL,

    NAME VARCHAR(255),
    VIBE_TYPE VARCHAR(255),
    SECTOR VARCHAR(255),

    ADDRESS_1 VARCHAR(255),
    ADDRESS_2 VARCHAR(255),
    CITY VARCHAR(255),
    STATE VARCHAR(255),
    STATE_CD VARCHAR(2),
    ZIP_CD VARCHAR(10),
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    TIME_ZONE VARCHAR(255),

    WEBSITE VARCHAR(255),
    PHONE_NUM VARCHAR(25),
    EMAIL VARCHAR(255),
    PRIMARY_CONTACT_NAME VARCHAR(255),

    IS_ACTIVE BOOLEAN,

    RECORD_CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATE_AUDIT_ID NUMBER(38,0),
    RECORD_UPDATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_AUDIT_ID NUMBER(38,0)

);

