CREATE TABLE IF NOT EXISTS DWH.ITEM (
    ITEM_ID NUMBER(38,0) NOT NULL DEFAULT DWH.ITEM_ID_SEQ.NEXTVAL,

    ITEM_CLASSIFICATION_ID NUMBER(38,0),

    NAME VARCHAR(255),
    NOTES VARCHAR(1000),
    
    IS_CUSTOM BOOLEAN,
    CUSTOM_ITEM_BUSINESS_ID NUMBER(38,0),

    ITEM_TAG_ARRAY ARRAY,

    RECORD_CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATE_AUDIT_ID NUMBER(38,0),
    RECORD_UPDATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_AUDIT_ID NUMBER(38,0)
);