CREATE TABLE IF NOT EXISTS DWH.ITEM_CLASSIFICATION (
    ITEM_CLASSIFICATION_ID NUMBER(38,0) NOT NULL DEFAULT DWH.ITEM_CLASSIFICATION_ID_SEQ.NEXTVAL,
    NAME VARCHAR(255),

    RECORD_CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATE_AUDIT_ID NUMBER(38,0),
    RECORD_UPDATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_AUDIT_ID NUMBER(38,0)
);
