CREATE TABLE IF NOT EXISTS DWH.SPECIALS (
    SPECIAL_ID NUMBER(38,0) NOT NULL DEFAULT DWH.SPECIAL_ID_SEQ.NEXTVAL,

    BUSINESS_ID NUMBER(38,0),
    ITEM_CLASSIFICATION_ID NUMBER(38,0),
    ITEM_ID NUMBER(38,0),
    SPECIAL_TYPE_ID NUMBER(38,0),
    
    DESCRIPTION VARCHAR(4000),
    COST NUMBER(38,2),
    DISCOUNT_DOLLARS NUMBER(38,2),
    DISCOUNT_PERCENTAGE NUMBER(5,4),

    DAY_OF_WEEK VARCHAR(10),
    IS_ALL_DAY BOOLEAN,
    START_TIME TIME,
    END_TIME TIME,

    EFF_START_DATE DATE, 
    EFF_END_DATE DATE,
    IS_ACTIVE BOOLEAN,

    RECORD_CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATE_AUDIT_ID NUMBER(38,0),
    RECORD_UPDATE_DT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_AUDIT_ID NUMBER(38,0),

    SPECIAL_LAST_VERIFIED_DT TIMESTAMP_NTZ(9)

);