CREATE TABLE IF NOT EXISTS STG.AUDIT (
    AUDIT_SID INT DEFAULT STG.AUDIT_SID_SEQ.NEXTVAL,
    START_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SUCCESS_FLG BOOLEAN,
    RESULT_MSG VARCHAR, 
    END_DT TIMESTAMP_NTZ,
    LOAD_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);