CREATE TABLE IF NOT EXISTS STG.WEEKLY_TEAM_MATCHUPS_LVL1(
    WEEK_NUMBER NUMBER(38,0),

    TEAM_KEY VARCHAR,
    TEAM_NAME VARCHAR,

    FULL_OBJECT OBJECT, 
    MATCHUPS_ARRAY ARRAY,

    SOURCE_FILE_NAME VARCHAR,

    LOAD_DT TIMESTAMP_NTZ(9)
)
;


