CREATE TABLE IF NOT EXISTS STG.WEEKLY_TEAM_MATCHUPS_LVL2(
    WEEK_NUMBER NUMBER(38,0),

    TEAM_KEY VARCHAR,
    TEAM_NAME VARCHAR,

    FULL_MATCHUP_OBJECT OBJECT,
    WEEK_START_DATE DATE, 
    WEEK_END_DATE DATE,

    SOURCE_FILE_NAME VARCHAR,

    LOAD_DT TIMESTAMP_NTZ(9)
)
;


