CREATE TABLE IF NOT EXISTS STG.WEEKLY_STATS_PLAYER_STATS (
    WEEK_NUMBER NUMBER(38,0),
    TEAM VARCHAR, 
    TEAM_KEY VARCHAR,
    PLAYER_KEY VARCHAR,
    PLAYER_NAME VARCHAR,
    PLAYER_TEAM VARCHAR,
    PLAYER_POSITION ARRAY,
    STAT_ID NUMBER(38,0),
    STAT_VALUE VARCHAR,
    LOAD_DT TIMESTAMP
);