CREATE TABLE IF NOT EXISTS STG.WEEKLY_STATS_PLAYERS (
    TEAM VARCHAR, 
    TEAM_KEY VARCHAR,
    PLAYER_KEY VARCHAR,
    PLAYER_NAME VARCHAR,
    PLAYER_TEAM VARCHAR,
    PLAYER_POSITION ARRAY,
    PLAYER_STATS VARIANT,
    LOAD_DT TIMESTAMP
);