CREATE TABLE IF NOT EXISTS STG.WEEKLY_STATS_TEAMS (
    TEAM VARCHAR, 
    TEAM_KEY VARCHAR,
    MANAGER_NICKNAME VARCHAR,
    MANAGER_EMAIL VARCHAR,
    ADDS INTEGER,
    FULL_TEAM_JSON_OBJ VARIANT,
    SOURCE_FILE VARCHAR,
    LOAD_DT TIMESTAMP
);