CREATE TABLE IF NOT EXISTS STG.WEEKLY_TEAM_MATCHUPS_LVL3(
    WEEK_NUMBER NUMBER(38,0),

    TEAM_KEY VARCHAR,
    TEAM_NAME VARCHAR,

    WEEK_START_DATE DATE, 
    WEEK_END_DATE DATE,
    MATCHUP_OBJECT OBJECT,

    SOURCE_FILE_NAME VARCHAR,

    LOAD_DT TIMESTAMP_NTZ(9)
)
;


