CREATE TABLE IF NOT EXISTS STG.WEEKLY_TEAM_MATCHUP_STATS(
    WEEK_NUMBER NUMBER(38,0),

    TEAM_KEY VARCHAR,
    TEAM_NAME VARCHAR,

    WEEK_START_DATE DATE, 
    WEEK_END_DATE DATE,

    STAT_ID NUMBER(38,0),
    STAT_VALUE VARCHAR,

    SOURCE_FILE_NAME VARCHAR,

    LOAD_DT TIMESTAMP_NTZ(9)
)
;


