CREATE TABLE IF NOT EXISTS STG.BIRD_SIMPLE_VARIANT_STAGE
COMMENT = 'Staging table for simple variant data, used on various BIRD ETL processes.'
 (
    MAIN_OBJ VARIANT,
    LOAD_DT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(9)
)
;
