USE ROLE CONNOR_ADMIN;
USE SCHEMA CONNOR.STG;

CREATE EXTERNAL FUNCTION IF NOT EXISTS STG.BIRD_GEO_REGION_REFRESH(REGION_TYPE VARCHAR, PARENT_REGION_CODE VARCHAR)
    RETURNS VARIANT
    API_INTEGRATION = AWS_LAMBDA_EXTERNAL_FUNCTIONS_GENERAL
    AS 'https://1dmrv6cveg.execute-api.us-east-2.amazonaws.com/prod/lambda-ebird-geo-region-refresh'
;
