USE ROLE CONNOR_ADMIN;
USE SCHEMA CONNOR.STG;

CREATE EXTERNAL FUNCTION IF NOT EXISTS STG.BIRD_GENERAL_REFRESHER(
    SWITCH_VALUE VARCHAR,
    ARG_1 VARCHAR,
    ARG_2 VARCHAR,
    ARG_3 VARCHAR)
    RETURNS VARIANT
    API_INTEGRATION = AWS_LAMBDA_EXTERNAL_FUNCTIONS_GENERAL
    AS 'https://1dmrv6cveg.execute-api.us-east-2.amazonaws.com/prod/lambda-ebird-general-refresher'
;
