CREATE OR REPLACE FUNCTION DWH.SLOP_CS_RANKINGS_LAST_N_WEEKS(WEEKS_BACK NUMBER)
RETURNS TABLE(
    TEAM_1_KEY VARCHAR,
    TEAM_1 VARCHAR,
    WINS NUMBER,
    LOSSES NUMBER,
    TIES NUMBER,
    TOTAL_GAMES NUMBER,
    TOTAL_CATEGORIES_WON NUMBER,
    TOTAL_CATEGORIES_LOST NUMBER,
    TOTAL_CATEGORIES_DRAWN NUMBER,
    WIN_PERCENTAGE NUMBER(23,5),
    CAT_DIFFERENTIAL VARCHAR,
    THROUGH_WEEKS NUMBER,
    WEEKS_INCLUDED ARRAY
)
AS
$$
SELECT 
    TEAM_1_KEY,
    ANY_VALUE(TEAM_1) AS TEAM_1,
    SUM(
        CASE WHEN TEAM_1_RESULT = 'W' THEN 1 ELSE 0 END
    ) AS WINS, 
    SUM(
        CASE WHEN TEAM_1_RESULT = 'L' THEN 1 ELSE 0 END
    ) AS LOSSES,
    SUM(
        CASE WHEN TEAM_1_RESULT = 'T' THEN 1 ELSE 0 END
    ) AS TIES,
    COUNT(*) AS TOTAL_GAMES,
    SUM(
        CATEGORIES_WON_BY_TEAM_1
    ) AS TOTAL_CATEGORIES_WON,
    SUM(
        CATEGORIES_WON_BY_TEAM_2
    ) AS TOTAL_CATEGORIES_LOST,
    SUM(
        9 - (CATEGORIES_WON_BY_TEAM_1 + CATEGORIES_WON_BY_TEAM_2)
    ) AS TOTAL_CATEGORIES_DRAWN,

    ROUND((WINS + (TIES * 0.5) ) / TOTAL_GAMES, 5) AS WIN_PERCENTAGE,

    concat(TOTAL_CATEGORIES_WON, '-', TOTAL_CATEGORIES_LOST, '-', TOTAL_CATEGORIES_DRAWN) AS CAT_DIFFERENTIAL,

    MAX(WEEK_NUMBER) AS THROUGH_WEEKS,
    ARRAY_AGG(DISTINCT WEEK_NUMBER) AS WEEKS_INCLUDED

FROM DWH.MATCHUPS_CROSSJOIN
WHERE WEEK_NUMBER > (SELECT MAX(WEEK_NUMBER) - WEEKS_BACK FROM DWH.MATCHUPS_CROSSJOIN)
GROUP BY TEAM_1_KEY
ORDER BY WIN_PERCENTAGE DESC
$$;