USE ROLE ZETA_BALL_ADMIN;
USE SCHEMA ZETA_BALL.STG;

CREATE EXTERNAL FUNCTION IF NOT EXISTS ZETA_BALL_REFRESH_LAMBDA_TRIGGER(TEAM_KEY VARCHAR, WEEKS_COMPLETED INT)
    RETURNS VARIANT
    API_INTEGRATION = AWS_LAMBDA_EXTERNAL_FUNCTIONS
    AS 'https://1dmrv6cveg.execute-api.us-east-2.amazonaws.com/prod/lambda-zeta-ball-refresh'
;
