CREATE STAGE IF NOT EXISTS BOOKS.RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE
URL = 's3://connors-misc-blob-for-blobs/books/acx/csv_stage/marketplace_breakdown_by_title/'
STORAGE_INTEGRATION = S3_FULL_INT
;

LIST @BOOKS.RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE;
