CREATE OR REPLACE TASK STG.REFRESH_WEEKLY_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 20 * * 1 US/Eastern'  -- 8:00 PM ET every Monday
  COMMENT = 'Run the STG.REFRESH_WEEKLY() procedure every Monday at 8 PM ET'
AS
  CALL STG.REFRESH_WEEKLY();


-- To activate the task after creation, run:
ALTER TASK STG.REFRESH_WEEKLY_TASK RESUME;

DESC TASK STG.REFRESH_WEEKLY_TASK;