CREATE TABLE IF NOT EXISTS DWH.MATCHUPS_CROSSJOIN(
    MATCHUPS_CROSSJOIN_SID NUMBER(38,0) DEFAULT DWH.MATCHUPS_CROSSJOIN_SEQ.NEXTVAL,
    WEEK_NUMBER NUMBER(38,0),
    MATCHUP_ID VARCHAR,
    TEAM_1 VARCHAR,
    TEAM_1_KEY VARCHAR,
    TEAM_2 VARCHAR,
    TEAM_2_KEY VARCHAR,

    CATEGORIES_WON_BY_TEAM_1 NUMBER(38,0),
    CATEGORIES_WON_BY_TEAM_2 NUMBER(38,0),
    TEAM_1_RESULT VARCHAR(1),

    LOAD_DT TIMESTAMP_NTZ(9)
)