CREATE TABLE IF NOT EXISTS DWH.WEEKLY_TEAM_TOTALS(
    WEEKLY_TEAM_TOTALS_SID NUMBER(38,0) DEFAULT DWH.WEEKLY_TEAM_TOTALS_SEQ.NEXTVAL,
    WEEK_NUMBER NUMBER(38,0),
    TEAM_KEY VARCHAR,
    TEAM VARCHAR,
    TOTAL_PTS NUMBER(38,0),
    TOTAL_REB NUMBER(38,0),
    TOTAL_AST NUMBER(38,0),
    TOTAL_BLK NUMBER(38,0),
    TOTAL_STL NUMBER(38,0),
    TOTAL_THREE_PM NUMBER(38,0),
    TOTAL_FGM NUMBER(38,0),
    TOTAL_FGA NUMBER(38,0),
    FG_PCT NUMBER(38,6),
    TOTAL_FTM NUMBER(38,0),
    TOTAL_FTA NUMBER(38,0),
    FT_PCT NUMBER(38,6),
    TOTAL_TOS NUMBER(38,0),

    LOAD_DT TIMESTAMP_NTZ(9)
)
;