CREATE TABLE IF NOT EXISTS DWH.WEEKLY_STATS(
    WEEKLY_STATS_SID NUMBER(38,0) DEFAULT DWH.WEEKLY_STATS_SEQ.NEXTVAL,
    WEEK_NUMBER NUMBER(38,0),
    TEAM_KEY VARCHAR, 
    TEAM VARCHAR,
    PLAYER_KEY VARCHAR,
    PLAYER_NAME VARCHAR,
    PLAYER_TEAM VARCHAR,
    POSITIONS_STARTED ARRAY,
    
    PTS NUMBER(38,0),
    REB NUMBER(38,0),
    AST NUMBER(38,0),
    BLK NUMBER(38,0),
    STL NUMBER(38,0),
    THREE_PM NUMBER(38,0),
    FGM NUMBER(38,0),
    FGA NUMBER(38,0),
    FTM NUMBER(38,0),
    FTA NUMBER(38,0),
    TOS NUMBER(38,0),

    LOAD_DT TIMESTAMP_NTZ(9)
)
;