CREATE OR REPLACE VIEW DWH.MATCHUPS_CROSSJOIN_FULL AS
SELECT 
    T1.TEAM, 
    T1.TEAM_KEY,
    T2.TEAM AS OPPONENT_TEAM,
    T2.TEAM_KEY AS OPPONENT_TEAM_KEY,
    T1.WEEK_NUMBER,
    T1.TOTAL_PTS AS TEAM_PTS,
    T2.TOTAL_PTS AS OPPONENT_PTS,
    CASE WHEN T1.TOTAL_PTS > T2.TOTAL_PTS THEN 'W' 
         WHEN T1.TOTAL_PTS < T2.TOTAL_PTS THEN 'L' 
         ELSE 'T' END AS PTS_RESULT,
    T1.TOTAL_REB AS TEAM_RBS,
    T2.TOTAL_REB AS OPPONENT_RBS,
    CASE WHEN T1.TOTAL_REB > T2.TOTAL_REB THEN 'W' 
         WHEN T1.TOTAL_REB < T2.TOTAL_REB THEN 'L' 
         ELSE 'T' END AS REB_RESULT,
    T1.TOTAL_AST AS TEAM_AST,
    T2.TOTAL_AST AS OPPONENT_AST,
    CASE WHEN T1.TOTAL_AST > T2.TOTAL_AST THEN 'W' 
         WHEN T1.TOTAL_AST < T2.TOTAL_AST THEN 'L' 
         ELSE 'T' END AS AST_RESULT,
    T1.TOTAL_BLK AS TEAM_BLKS,
    T2.TOTAL_BLK AS OPPONENT_BLKS,
    CASE WHEN T1.TOTAL_BLK > T2.TOTAL_BLK THEN 'W' 
         WHEN T1.TOTAL_BLK < T2.TOTAL_BLK THEN 'L' 
         ELSE 'T' END AS BLK_RESULT,
    T1.TOTAL_STL AS TEAM_STLS,
    T2.TOTAL_STL AS OPPONENT_STLS,
    CASE WHEN T1.TOTAL_STL > T2.TOTAL_STL THEN 'W' 
         WHEN T1.TOTAL_STL < T2.TOTAL_STL THEN 'L' 
         ELSE 'T' END AS STL_RESULT,
    T1.TOTAL_THREE_PM AS TEAM_3PM,
    T2.TOTAL_THREE_PM AS OPPONENT_3PM,
    CASE WHEN T1.TOTAL_THREE_PM > T2.TOTAL_THREE_PM THEN 'W' 
         WHEN T1.TOTAL_THREE_PM < T2.TOTAL_THREE_PM THEN 'L' 
         ELSE 'T' END AS THREE_PM_RESULT,
    T1.FG_PCT AS TEAM_FG_PCT,
    T2.FG_PCT AS OPPONENT_FG_PCT,
    CASE WHEN T1.FG_PCT > T2.FG_PCT THEN 'W' 
            WHEN T1.FG_PCT < T2.FG_PCT THEN 'L' 
            ELSE 'T' END AS FG_PCT_RESULT,
    T1.FT_PCT AS TEAM_FT_PCT,
    T2.FT_PCT AS OPPONENT_FT_PCT,
    CASE WHEN T1.FT_PCT > T2.FT_PCT THEN 'W' 
            WHEN T1.FT_PCT < T2.FT_PCT THEN 'L' 
            ELSE 'T' END AS FT_PCT_RESULT,
    T1.TOTAL_TOS AS TEAM_TOS,
    T2.TOTAL_TOS AS OPPONENT_TOS,
    CASE WHEN T1.TOTAL_TOS < T2.TOTAL_TOS THEN 'W' 
         WHEN T1.TOTAL_TOS > T2.TOTAL_TOS THEN 'L' 
         ELSE 'T' END AS TOS_RESULT
FROM DWH.WEEKLY_TEAM_TOTALS T1 
INNER JOIN DWH.WEEKLY_TEAM_TOTALS T2 
    ON T1.TEAM_KEY <> T2.TEAM_KEY
    AND T1.WEEK_NUMBER = T2.WEEK_NUMBER
;