CREATE OR REPLACE VIEW DWH.MATCHUPS_CROSSJOIN_TEAM_SUMMARIES 
AS
SELECT 
    TEAM_KEY,
    ANY_VALUE(TEAM) AS NAME,
    ROUND(
        SUM(CASE WHEN PTS_RESULT = 'W' THEN 1 ELSE 0 END) 
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS PTS_WIN_PCT,
    AVG(TEAM_PTS) AS AVG_WEEKLY_PTS,
    ROUND(
        SUM(CASE WHEN REB_RESULT = 'W' THEN 1 ELSE 0 END) 
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS REBS_WIN_PCT,
    AVG(TEAM_RBS) AS AVG_WEEKLY_RBS,
    ROUND(
        SUM(CASE WHEN AST_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS ASTS_WIN_PCT,
    AVG(TEAM_AST) AS AVG_WEEKLY_AST,
    ROUND(
        SUM(CASE WHEN BLK_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS BLKS_WIN_PCT,
    AVG(TEAM_BLKS) AS AVG_WEEKLY_BLKS,
    ROUND(
        SUM(CASE WHEN STL_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS STLS_WIN_PCT,
    AVG(TEAM_STLS) AS AVG_WEEKLY_STLS,
    ROUND(
        SUM(CASE WHEN THREE_PM_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS THREE_PM_WIN_PCT,
    AVG(TEAM_3PM) AS AVG_WEEKLY_3PM,
    ROUND(
        SUM(CASE WHEN FG_PCT_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS FG_PCT_WIN_PCT,
    AVG(TEAM_FG_PCT) AS AVG_WEEKLY_FG_PCT,
    ROUND(
        SUM(CASE WHEN FT_PCT_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS FT_PCT_WIN_PCT,
    AVG(TEAM_FT_PCT) AS AVG_WEEKLY_FT_PCT,
    ROUND(
        SUM(CASE WHEN TOS_RESULT = 'W' THEN 1 ELSE 0 END)
        / COUNT(DISTINCT WEEK_NUMBER, OPPONENT_TEAM_KEY)::FLOAT, 6
        )
        *(100) AS TOS_WIN_PCT,
    AVG(TEAM_TOS) AS AVG_WEEKLY_TOS
FROM DWH.MATCHUPS_CROSSJOIN_FULL
GROUP BY TEAM_KEY
;