CREATE OR REPLACE VIEW DWH.SLOP_CS_RANKINGS AS
SELECT 
    TEAM_1_KEY,
    ANY_VALUE(TEAM_1) AS TEAM_1,
    SUM(
        CASE WHEN TEAM_1_RESULT = 'W' THEN 1 ELSE 0 END
    ) AS WINS, 
    SUM(
        CASE WHEN TEAM_1_RESULT = 'L' THEN 1 ELSE 0 END
    ) AS LOSSES,
    SUM(
        CASE WHEN TEAM_1_RESULT = 'T' THEN 1 ELSE 0 END
    ) AS TIES,
    COUNT(*) AS TOTAL_GAMES,
    SUM(
        CATEGORIES_WON_BY_TEAM_1
    ) AS TOTAL_CATEGORIES_WON,
    SUM(
        CATEGORIES_WON_BY_TEAM_2
    ) AS TOTAL_CATEGORIES_LOST,
    SUM(
        9 - (CATEGORIES_WON_BY_TEAM_1 + CATEGORIES_WON_BY_TEAM_2)
    ) AS TOTAL_CATEGORIES_DRAWN,

    ROUND((WINS + (TIES * 0.5) ) / TOTAL_GAMES, 5) AS WIN_PERCENTAGE,

    concat(TOTAL_CATEGORIES_WON, '-', TOTAL_CATEGORIES_LOST, '-', TOTAL_CATEGORIES_DRAWN) AS CAT_DIFFERENTIAL,

    MAX(WEEK_NUMBER) AS THROUGH_WEEKS

FROM DWH.MATCHUPS_CROSSJOIN
GROUP BY TEAM_1_KEY
ORDER BY WIN_PERCENTAGE DESC
;