CREATE OR REPLACE VIEW DWH.SLOP_STAT_RANKINGS AS

SELECT 
*,
CASE WHEN STAT_NAME = 'TO' THEN RANK() OVER (PARTITION BY STAT_NAME ORDER BY STAT)
ELSE RANK() OVER (PARTITION BY STAT_NAME ORDER BY STAT DESC) END
 AS STAT_RANKING
FROM (
SELECT 
    TEAM, 
    'PTS' AS STAT_NAME,
    SUM(TOTAL_PTS)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT 
    TEAM, 
    'REB' AS STAT_NAME,
    SUM(TOTAL_REB)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM, 
    'AST' AS STAT_NAME,
    SUM(TOTAL_AST)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM,
    'STL' AS STAT_NAME,
    SUM(TOTAL_STL)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM,
    'BLK' AS STAT_NAME,
    SUM(TOTAL_BLK)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM,
    '3PM' AS STAT_NAME,
    SUM(TOTAL_THREE_PM)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM,
    'FT%' AS STAT_NAME,
    ROUND(
        SUM(TOTAL_FTM)::NUMBER(38,6) / NULLIF(SUM(TOTAL_FTA)::NUMBER(38,6), 0), 6
    ) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM,
    'FG%' AS STAT_NAME,
    ROUND(
        SUM(TOTAL_FGM)::NUMBER(38,6) / NULLIF(SUM(TOTAL_FGA)::NUMBER(38,6), 0), 6
    ) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
UNION ALL
SELECT
    TEAM,
    'TO' AS STAT_NAME,
    SUM(TOTAL_TOS)::NUMBER(38,6) AS STAT
FROM DWH.WEEKLY_TEAM_TOTALS
GROUP BY TEAM
);