CREATE TABLE IF NOT EXISTS BOOKS.RPT.DAILY_SALES_REPORT (
    BOOK_SID INT,
    BOOK_VERSION_SID INT,
    BOOK_TITLE VARCHAR,
    VERSION_TYPE VARCHAR,
    VERSION_LANGUAGE VARCHAR,
    MARKETPLACE VARCHAR,
    ROYALTY_DATE DATE,
    NET_UNITS_SOLD INT,
    ROYALTY_IN_USD FLOAT
)
;