CREATE TABLE IF NOT EXISTS BOOKS.CONFIG.BOOK_VERSIONS (
    BOOK_VERSION_SID INT NOT NULL UNIQUE DEFAULT CONFIG.BOOK_VERSION_SID_SEQ.NEXTVAL,
    BOOK_SID INT NOT NULL,
    BOOK_VERSION_UNIQUE_ID VARCHAR NOT NULL,
    BOOK_VERSION_UNIQUE_ID_TYPE VARCHAR NOT NULL,
    BOOK_TITLE VARCHAR,
    VERSION_TITLE VARCHAR,
    VERSION_TYPE VARCHAR,
    VERSION_LANGUAGE VARCHAR
);

TRUNCATE TABLE BOOKS.CONFIG.BOOK_VERSIONS;

INSERT INTO BOOKS.CONFIG.BOOK_VERSIONS (
    BOOK_SID,  BOOK_VERSION_UNIQUE_ID, BOOK_VERSION_UNIQUE_ID_TYPE,
    VERSION_TITLE, VERSION_TYPE, VERSION_LANGUAGE
)

VALUES

(12, '9781537293424', 'ISBN', $$Rothaker: A Dark Psychological Suspense Novel$$,         'Print', 'EN'),
(11, '9781537294711', 'ISBN', $$Everett: A Dark Psychological Suspense Novel$$,           'Print', 'EN'),
(13, '9781724682000', 'ISBN', $$The Intern: A Dark Thriller$$,                            'Print', 'EN'),
(1,  '9781733957007', 'ISBN', $$The Numbers Killer$$,                                     'Print', 'EN'),
(2,  '9781733957038', 'ISBN', $$Pretty Little Girls$$,                                    'Print', 'EN'),
(15, '9781733957052', 'ISBN', $$Only One Cure: A Medical Thriller$$,                      'Print', 'EN'),
(3,  '9781733957076', 'ISBN', $$When They Find Us$$,                                      'Print', 'EN'),
(18, '9781954447011', 'ISBN', $$Lauren's Secret: Full-Out$$,                              'Print', 'EN'),
(4,  '9781954447028', 'ISBN', $$Ripple of Doubt$$,                                        'Print', 'EN'),
(16, '9781954447134', 'ISBN', $$Only One Wave: The Tsunami Effect$$,                      'Print', 'EN'),
(5,  '9781954447172', 'ISBN', $$The Groom Went Missing$$,                                 'Print', 'EN'),
(6,  '9781954447226', 'ISBN', $$Vanished On Vacation$$,                                   'Print', 'EN'),
(7,  '9781954447240', 'ISBN', $$The Atonement Murders$$,                                  'Print', 'EN'),
(8,  '9781954447325', 'ISBN', $$The Ones They Buried$$,                                   'Print', 'EN'),
(9,  '9781954447356', 'ISBN', $$The Bad Neighbor$$,                                       'Print', 'EN'),
(17, '9781954447370', 'ISBN', $$When She Escaped: A Thriller$$,                           'Print', 'EN'),
(17, '9781954447387', 'ISBN', $$When She Escaped: A Thriller$$,                           'Print', 'EN'),
(10, '9781954447400', 'ISBN', $$LIES IN THE SNOW$$,                                       'Print', 'EN'),
(19, '9781954447530', 'ISBN', $$The Last Seat: A Thriller$$,                              'Print', 'EN'),
(14, '9781973750710', 'ISBN', $$Only Wrong Once: A Suspense Thriller$$,                   'Print', 'EN'),
(17, '9798245222059', 'ISBN', $$QUANDO È FUGGITA$$,                                       'Print', 'IT'),
(1,  '9798268535792', 'ISBN', $$LE TUEUR DES CHIFFRES: Les Enquêtes de Victoria Heslin$$, 'Print', 'FR'),
(3,  '9798268588217', 'ISBN', $$QUAND ILS NOUS TROUVENT: Les Enquêtes de Victoria Heslin$$,'Print', 'FR'),
(2,  '9798268708189', 'ISBN', $$JOLIES PETITES FILLES: Les Enquêtes de Victoria Heslin 2$$,'Print', 'FR'),
(1,  '9798269295619', 'ISBN', $$IL KILLER DEI NUMERI: Le indagini di Victoria Heslin 1$$, 'Print', 'IT'),
(2,  '9798269299129', 'ISBN', $$BAMBINE PER BENE: Le indagini di Victoria Heslin 2$$,     'Print', 'IT'),
(3,  '9798269437958', 'ISBN', $$QUANDO CI TROVERANNO: Le indagini di Victoria Heslin 3$$, 'Print', 'IT'),
(4,  '9798269555270', 'ISBN', $$L'OMBRA DEL DUBBIO: Le indagini di Victoria Heslin$$,     'Print', 'IT'),
(4,  '9798269560496', 'ISBN', $$ ONDE DE DOUTE: Les Enquêtes de Victoria Heslin$$,        'Print', 'FR'),
(14, '9798269885308', 'ISBN', $$UNE SEULE ERREUR: Les Enquêtes Médicales de FBI & CDC - 1$$,'Print','FR'),
(15, '9798269992778', 'ISBN', $$UN SEUL REMÈDE: Les Enquêtes Médicales de FBI & CDC - 2$$,'Print', 'FR'),
(16, '9798270024789', 'ISBN', $$UNE SEULE VAGUE : L'EFFET TSUNAMI: Les Enquêtes Médicales de FBI & CDC - 3$$,'Print','FR'),
(5,  '9798270134570', 'ISBN', $$LE MARIÉ A DISPARU: Les Enquêtes de Victoria Heslin$$,    'Print', 'FR'),
(5,  '9798270142551', 'ISBN', $$LO SPOSO SCOMPARSO: Le indagini di Victoria Heslin$$,     'Print', 'IT'),
(6,  '9798270169626', 'ISBN', $$DISPARUE EN VACANCES: Les Enquêtes de Victoria Heslin$$,  'Print', 'FR'),
(6,  '9798270177973', 'ISBN', $$SCOMPARSA IN VACANZA: Le indagini di Victoria Heslin 6$$, 'Print', 'IT'),
(7,  '9798270550394', 'ISBN', $$DELITTI PER ESPIARE: Le indagini di Victoria Heslin 7$$,  'Print', 'IT'),
(7,  '9798270672553', 'ISBN', $$ LES MEURTRES DE L'EXPIATION: Les Enquêtes de Victoria Heslin 7$$,'Print','FR'),
(8,  '9798270702403', 'ISBN', $$CEUX QU'ILS ONT ENTERRÉS: Les Enquêtes de Victoria Heslin$$,'Print','FR'),
(10, '9798270963828', 'ISBN', $$MENSONGES DANS LA NEIGE: Les Enquêtes de Victoria Heslin - 10$$,'Print','FR'),
(10, '9798271105524', 'ISBN', $$MENZOGNE SOTTO LA NEVE: Le indagini di Victoria Heslin 10$$,'Print','IT'),
(8,  '9798271154010', 'ISBN', $$I SEPOLTI: Le indagini di Victoria Heslin 8$$,            'Print', 'IT'),
(9,  '9798271164149', 'ISBN', $$LE MAUVAIS VOISIN: Les Enquêtes de Victoria Heslin$$,     'Print', 'FR'),
(9,  '9798271413803', 'ISBN', $$IL VICINO PERICOLOSO: Le indagini di Victoria Heslin 9$$, 'Print', 'IT'),
(16, '9798271854095', 'ISBN', $$SOLO UN'ONDA: EFFETTO TSUNAMI: La Serie Thriller Medici FBI & CDC 3$$,'Print','IT'),
(15, '9798271860942', 'ISBN', $$SOLO UNA CURA: La Serie Thriller Medici FBI & CDC 2$$,    'Print', 'IT'),
(14, '9798271894848', 'ISBN', $$SOLO UN ERRORE: La Serie Thriller Medici FBI & CDC 1$$,   'Print', 'IT'),

(18, 'B01H7QSKHE', 'ASIN', $$Lauren's Secret: Full-Out$$,                                'eBook', 'EN'),
(12, 'B01L0ZXPPK', 'ASIN', $$Rothaker: A Dark Psychological Suspense Novel$$,            'eBook', 'EN'),
(11, 'B01L0ZXUT6', 'ASIN', $$Everett: A Dark Psychological Suspense Novel$$,              'eBook', 'EN'),
(20, 'B07H1MPFZS', 'ASIN', $$Brooke Walton Series 1-3$$,                                 'eBook', 'EN'),
(13, 'B07HP9XGY8', 'ASIN', $$The Intern: A Dark Thriller$$,                               'eBook', 'EN'),
(1,  'B07SFG39WT', 'ASIN', $$The Numbers Killer$$,                                        'eBook', 'EN'),
(2,  'B07V6M12JS', 'ASIN', $$Pretty Little Girls$$,                                       'eBook', 'EN'),
(15, 'B0845YLJ7V', 'ASIN', $$Only One Cure: A Medical Thriller$$,                         'eBook', 'EN'),
(3,  'B08BTMLCTT', 'ASIN', $$When They Find Us$$,                                         'eBook', 'EN'),
(4,  'B08NHWFMCV', 'ASIN', $$Ripple of Doubt$$,                                           'eBook', 'EN'),
(21, 'B08RY3QMBY', 'ASIN', $$Agent Victoria Heslin Series, Books 1-3: Mystery Thrillers$$,'eBook', 'EN'),
(16, 'B09CZHHFVN', 'ASIN', $$Only One Wave: The Tsunami Effect$$,                         'eBook', 'EN'),
(5,  'B09M643686', 'ASIN', $$The Groom Went Missing$$,                                    'eBook', 'EN'),
(22, 'B09NF1R82H', 'ASIN', $$FBI & CDC Thriller Series Books 1-3$$,                       'eBook', 'EN'),
(6,  'B09YJ79K6X', 'ASIN', $$Vanished On Vacation$$,                                      'eBook', 'EN'),
(7,  'B0BFT9XBJZ', 'ASIN', $$The Atonement Murders$$,                                     'eBook', 'EN'),
(8,  'B0CD8VGFVK', 'ASIN', $$The Ones They Buried$$,                                      'eBook', 'EN'),
(9,  'B0D2KSPL5L', 'ASIN', $$The Bad Neighbor$$,                                          'eBook', 'EN'),
(15, 'B0DJ38BDF4', 'ASIN', $$UN SEUL REMÈDE: Les Enquêtes Médicales de FBI & CDC - 2$$,   'eBook', 'FR'),
(16, 'B0DTKKQMWX', 'ASIN', $$UNE SEULE VAGUE : L'EFFET TSUNAMI: Les Enquêtes Médicales de FBI & CDC - 3$$,'eBook','FR'),
(17, 'B0F54LSYZN', 'ASIN', $$When She Escaped: A Thriller$$,                              'eBook', 'EN'),
(14, 'B0FMPGWQ7V', 'ASIN', $$UNE SEULE ERREUR: Les Enquêtes Médicales de FBI & CDC - 1$$, 'eBook', 'FR'),
(2,  'B0FSMSZPPL', 'ASIN', $$JOLIES PETITES FILLES: Les Enquêtes de Victoria Heslin 2$$,  'eBook', 'FR'),
(1,  'B0FSN11Q5L', 'ASIN', $$LE TUEUR DES CHIFFRES: Les Enquêtes de Victoria Heslin$$,    'eBook', 'FR'),
(3,  'B0FSSN4D15', 'ASIN', $$QUAND ILS NOUS TROUVENT: Les Enquêtes de Victoria Heslin$$,  'eBook', 'FR'),
(4,  'B0FSSX5XMY', 'ASIN', $$ ONDE DE DOUTE: Les Enquêtes de Victoria Heslin$$,           'eBook', 'FR'),
(6,  'B0FST7LDPY', 'ASIN', $$DISPARUE EN VACANCES: Les Enquêtes de Victoria Heslin$$,     'eBook', 'FR'),
(5,  'B0FSTGJHS8', 'ASIN', $$LE MARIÉ A DISPARU: Les Enquêtes de Victoria Heslin$$,       'eBook', 'FR'),
(7,  'B0FSYD8T25', 'ASIN', $$ LES MEURTRES DE L'EXPIATION: Les Enquêtes de Victoria Heslin 7$$,'eBook','FR'),
(8,  'B0FSYWY2FQ', 'ASIN', $$CEUX QU'ILS ONT ENTERRÉS: Les Enquêtes de Victoria Heslin$$, 'eBook', 'FR'),
(9,  'B0FT1KW7ST', 'ASIN', $$LE MAUVAIS VOISIN: Les Enquêtes de Victoria Heslin$$,        'eBook', 'FR'),
(10, 'B0FV3S66HV', 'ASIN', $$LIES IN THE SNOW$$,                                          'eBook', 'EN'),
(3,  'B0FVCCNPDD', 'ASIN', $$QUANDO CI TROVERANNO: Le indagini di Victoria Heslin 3$$,    'eBook', 'IT'),
(1,  'B0FVCG3TWP', 'ASIN', $$IL KILLER DEI NUMERI: Le indagini di Victoria Heslin 1$$,    'eBook', 'IT'),
(2,  'B0FVCNMSM5', 'ASIN', $$BAMBINE PER BENE: Le indagini di Victoria Heslin 2$$,        'eBook', 'IT'),
(5,  'B0FVDZ578Q', 'ASIN', $$LO SPOSO SCOMPARSO: Le indagini di Victoria Heslin$$,        'eBook', 'IT'),
(4,  'B0FVFW5C5S', 'ASIN', $$L'OMBRA DEL DUBBIO: Le indagini di Victoria Heslin$$,        'eBook', 'IT'),
(7,  'B0FVKWN1JM', 'ASIN', $$DELITTI PER ESPIARE: Le indagini di Victoria Heslin 7$$,     'eBook', 'IT'),
(6,  'B0FVNBVJ22', 'ASIN', $$SCOMPARSA IN VACANZA: Le indagini di Victoria Heslin 6$$,    'eBook', 'IT'),
(10, 'B0FVTLF5W7', 'ASIN', $$MENSONGES DANS LA NEIGE: Les Enquêtes de Victoria Heslin - 10$$,'eBook','FR'),
(8,  'B0FVW51VYC', 'ASIN', $$I SEPOLTI: Le indagini di Victoria Heslin 8$$,               'eBook', 'IT'),
(9,  'B0FW7LYXPX', 'ASIN', $$IL VICINO PERICOLOSO: Le indagini di Victoria Heslin 9$$,    'eBook', 'IT'),
(10, 'B0FZD9F4BH', 'ASIN', $$MENZOGNE SOTTO LA NEVE: Le indagini di Victoria Heslin 10$$, 'eBook', 'IT'),
(15, 'B0GCXQJXMZ', 'ASIN', $$SOLO UNA CURA: La Serie Thriller Medici FBI & CDC 2$$,       'eBook', 'IT'),
(14, 'B0GCXQXCY8', 'ASIN', $$SOLO UN ERRORE: La Serie Thriller Medici FBI & CDC 1$$,      'eBook', 'IT'),
(16, 'B0GD2CZNDL', 'ASIN', $$SOLO UN'ONDA: EFFETTO TSUNAMI: La Serie Thriller Medici FBI & CDC 3$$,'eBook','IT'),
(17, 'B0GG9LLFZS', 'ASIN', $$QUANDO È FUGGITA$$,                                          'eBook', 'IT'),
(15, 'B0GJTTZ7PF', 'ASIN', $$NUR EIN HEILMITTEL: FBI & CDC Thrillerserie$$,               'eBook', 'DE'),
(19, 'B0GQVJMJX3', 'ASIN', $$The Last Seat: A Thriller$$,                                 'eBook', 'EN'),
(3,  'B0GX2WV4CZ', 'ASIN', $$CUANDO NOS ENCUENTREN: Las investigaciones de Victoria Heslin 3$$,'eBook','ES'),
(4,  'B0GZPF9JBL', 'ASIN', $$LA SOMBRA DE LA DUDA: Las investigaciones de Victoria Heslin 4$$,'eBook','ES'),
(2,  'B0GZS3BSHD', 'ASIN', $$NIÑAS PERFECTAS: Las investigaciones de Victoria Heslin 2$$, 'eBook', 'ES'),
(1,  'B0H15GGWJL', 'ASIN', $$EL ASESINO DE LOS NÚMEROS: Las investigaciones de Victoria Heslin 1$$,'eBook','ES'),
(16, 'B0GJTLT2P1', 'ASIN', $$NUR EINE WELLE: DER TSUNAMI-EFFEKT: FBI & CDC Thrillerserie 3$$, 'eBook', 'DE'),
(14, 'B075XN3QHD', 'ASIN', $$Only Wrong Once: A Suspense Thriller$$, 'eBook', 'EN'),
(14, 'B0GJSXG7N3', 'ASIN', $$NUR EINMAL FALSCH: FBI & CDC Thrillerserie 1$$, 'eBook', 'DE'),
(9, '9781954447301', 'ISBN', $$The Bad Neighbor$$, 'Print', 'EN'),
(8, '9781954447318', 'ISBN', $$The Ones They Buried$$, 'Print', 'EN'),
(14, '9798245707471', 'ISBN', $$NUR EINMAL FALSCH: FBI & CDC Thrillerserie 1$$, 'Print', 'DE'),
(5, 'B0GX2ZW2SJ', 'ASIN', $$DESAPARECIÓ EL NOVIO: Las investigaciones de Victoria Heslin 5$$, 'eBook', 'ES')
;


UPDATE BOOKS.CONFIG.BOOK_VERSIONS
    SET BOOK_TITLE = LU.TITLE
    FROM BOOKS.CONFIG.BOOKS LU
    WHERE BOOK_VERSIONS.BOOK_SID = LU.BOOK_SID
    ;