CREATE TABLE IF NOT EXISTS BOOKS.CONFIG.CROSSWALK (
    RAW_TABLE_NAME VARCHAR,
    RAW_COLUMN_NUMBER INT,
    RAW_COLUMN_NAME VARCHAR,
    TARGET_TABLE_NAME VARCHAR,
    TARGET_COLUMN_NAME VARCHAR,
    TARGET_DATA_TYPE VARCHAR
);


TRUNCATE TABLE BOOKS.CONFIG.CROSSWALK;

INSERT INTO BOOKS.CONFIG.CROSSWALK
(RAW_TABLE_NAME, RAW_COLUMN_NUMBER, RAW_COLUMN_NAME,
TARGET_TABLE_NAME, TARGET_COLUMN_NAME, TARGET_DATA_TYPE)
VALUES

-- KDP_COMBINED_SALES
('RAW.KDP_COMBINED_SALES_STAGE', 1,  '"Royalty Date"',                     'KDP.COMBINED_SALES', 'ROYALTY_DATE',             'DATE'),
('RAW.KDP_COMBINED_SALES_STAGE', 2,  '"Title"',                            'KDP.COMBINED_SALES', 'TITLE',                    'VARCHAR(250)'),
('RAW.KDP_COMBINED_SALES_STAGE', 3,  '"Author Name"',                      'KDP.COMBINED_SALES', 'AUTHOR_NAME',              'VARCHAR(250)'),
('RAW.KDP_COMBINED_SALES_STAGE', 4,  '"ASIN/ISBN"',                        'KDP.COMBINED_SALES', 'ASIN_ISBN',                'VARCHAR(25)'),
('RAW.KDP_COMBINED_SALES_STAGE', 5,  '"Marketplace"',                      'KDP.COMBINED_SALES', 'MARKETPLACE',              'VARCHAR(250)'),
('RAW.KDP_COMBINED_SALES_STAGE', 6,  '"Royalty Type"',                     'KDP.COMBINED_SALES', 'ROYALTY_TYPE',             'VARCHAR(250)'),
('RAW.KDP_COMBINED_SALES_STAGE', 7,  '"Transaction Type"',                 'KDP.COMBINED_SALES', 'TRANSACTION_TYPE',         'VARCHAR(250)'),
('RAW.KDP_COMBINED_SALES_STAGE', 8,  '"Units Sold"',                       'KDP.COMBINED_SALES', 'UNITS_SOLD',               'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 9,  '"Units Refunded"',                   'KDP.COMBINED_SALES', 'UNITS_REFUNDED',           'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 10, '"Net Units Sold"',                   'KDP.COMBINED_SALES', 'NET_UNITS_SOLD',           'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 11, '"Avg. List Price without tax"',      'KDP.COMBINED_SALES', 'AVG_LIST_PRICE_WOUT_TAX',  'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 12, '"Avg. Offer Price without tax"',     'KDP.COMBINED_SALES', 'AVG_OFFER_PRICE_WOUT_TAX', 'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 13, '"Avg. Delivery/Manufacturing cost"', 'KDP.COMBINED_SALES', 'AVG_DELIV_MANUFACT_COST',  'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 14, '"Royalty"',                          'KDP.COMBINED_SALES', 'ROYALTY',                  'NUMBER(38,2)'),
('RAW.KDP_COMBINED_SALES_STAGE', 15, '"Currency"',                         'KDP.COMBINED_SALES', 'CURRENCY',                 'VARCHAR(25)'),

-- KDP_KENP_STAGE
('RAW.KDP_KENP_STAGE', 1, '"Date"',           'KDP.KENP', 'KENP_DATE',      'DATE'),
('RAW.KDP_KENP_STAGE', 2, '"Title"',          'KDP.KENP', 'TITLE',          'VARCHAR(250)'),
('RAW.KDP_KENP_STAGE', 3, '"Author Name"',    'KDP.KENP', 'AUTHOR_NAME',    'VARCHAR(250)'),
('RAW.KDP_KENP_STAGE', 4, '"eBook ASIN"',     'KDP.KENP', 'EBOOK_ASIN',     'VARCHAR(25)'),
('RAW.KDP_KENP_STAGE', 5, '"Audiobook ASIN"', 'KDP.KENP', 'AUDIOBOOK_ASIN', 'VARCHAR(25)'),
('RAW.KDP_KENP_STAGE', 6, '"Audible ASIN"',   'KDP.KENP', 'AUDIBLE_ASIN',   'VARCHAR(25)'),
('RAW.KDP_KENP_STAGE', 7, '"Marketplace"',    'KDP.KENP', 'MARKETPLACE',    'VARCHAR(250)'),
('RAW.KDP_KENP_STAGE', 8, '"KENP"',           'KDP.KENP', 'KENP',           'NUMBER(38,0)'),

-- ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 1,  '"Royalty Earner"', 'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'ROYALTY_EARNER', 'VARCHAR(250)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 2,  '"Product ID"',     'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'PRODUCT_ID',     'VARCHAR(50)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 3,  '"Author"',         'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'AUTHOR',         'VARCHAR(250)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 4,  '"Title"',          'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'TITLE',          'VARCHAR(250)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 5,  '"Digital ISBN"',   'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'DIGITAL_ISBN',    'VARCHAR(50)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 6,  '"AU"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'AU',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 7,  '"CA"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'CA',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 8,  '"DE"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'DE',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 9,  '"IN"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'IN',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 10, '"JP"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'JP',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 11, '"UK"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'UK',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 12, '"US"',             'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'US',             'NUMBER(38,10)'),
('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 13, '"Total"',          'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 'TOTAL',          'NUMBER(38,10)'),

-- ACX_ROYALTIES_BY_TITLE_STAGE
-- Source has two header rows; row 0 is category group, row 1 is sub-column name. RAW_COLUMN_NAME reflects the row-1 sub-column name.
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 1,  '"Royalty Earner"',                                   'ACX.ROYALTIES_BY_TITLE', 'ROYALTY_EARNER',                              'VARCHAR(250)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 2,  '"Product ID"',                                       'ACX.ROYALTIES_BY_TITLE', 'PRODUCT_ID',                                  'VARCHAR(50)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 3,  '"Author"',                                           'ACX.ROYALTIES_BY_TITLE', 'AUTHOR',                                      'VARCHAR(250)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 4,  '"Title"',                                            'ACX.ROYALTIES_BY_TITLE', 'TITLE',                                       'VARCHAR(250)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 5,  '"Digital ISBN"',                                     'ACX.ROYALTIES_BY_TITLE', 'DIGITAL_ISBN',                                'VARCHAR(50)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 6,  '"Member Credit Sales and TQLs - Net Units"',         'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CREDIT_TQL_NET_UNITS',                 'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 7,  '"Member Credit Sales and TQLs - TQLs"',              'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CREDIT_TQL_TQLS',                      'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 8,  '"Member Credit Sales and TQLs - Net Royalties"',     'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CREDIT_TQL_NET_ROYALTIES_EARNED',      'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 9,  '"Member Credit Sales AL - Net Units"',               'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CREDIT_AL_NET_UNITS',                  'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 10, '"Member Credit Sales AL - Net Royalties"',           'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CREDIT_AL_NET_ROYALTIES_EARNED',       'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 11, '"Member Cash Sales ALOP - Net Units"',               'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CASH_ALOP_NET_UNITS',                  'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 12, '"Member Cash Sales ALOP - Net Royalties"',           'ACX.ROYALTIES_BY_TITLE', 'MEMBER_CASH_ALOP_NET_ROYALTIES_EARNED',       'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 13, '"Non-Member Cash Sales ALC - Net Units"',            'ACX.ROYALTIES_BY_TITLE', 'NON_MEMBER_CASH_ALC_NET_UNITS',               'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 14, '"Non-Member Cash Sales ALC - Net Royalties"',        'ACX.ROYALTIES_BY_TITLE', 'NON_MEMBER_CASH_ALC_NET_ROYALTIES_EARNED',    'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 15, '"On-Demand - Listening Minutes"',                    'ACX.ROYALTIES_BY_TITLE', 'ON_DEMAND_LISTENING_MINUTES',                 'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 16, '"On-Demand - Net Royalties"',                        'ACX.ROYALTIES_BY_TITLE', 'ON_DEMAND_NET_ROYALTIES_EARNED',              'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 17, '"Total - Net Units"',                                'ACX.ROYALTIES_BY_TITLE', 'TOTAL_NET_UNITS',                             'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 18, '"Total - TQLs"',                                     'ACX.ROYALTIES_BY_TITLE', 'TOTAL_TQLS',                                  'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 19, '"Total - Listening Minutes"',                        'ACX.ROYALTIES_BY_TITLE', 'TOTAL_LISTENING_MINUTES',                     'NUMBER(38,2)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 20, '"Total - Net Royalties Earned"',                     'ACX.ROYALTIES_BY_TITLE', 'TOTAL_NET_ROYALTIES_EARNED',                  'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 21, '"Total - Adjustments"',                              'ACX.ROYALTIES_BY_TITLE', 'TOTAL_ADJUSTMENTS',                           'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 22, '"Total - Recoupments"',                              'ACX.ROYALTIES_BY_TITLE', 'TOTAL_RECOUPMENTS',                           'NUMBER(38,10)'),
('RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 23, '"Total - Net Royalties"',                            'ACX.ROYALTIES_BY_TITLE', 'TOTAL_NET_ROYALTIES',                         'NUMBER(38,10)'),

-- ACX_SALES_DETAIL_MEMBER_VALUE_STAGE
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 1,  '"Amazon Customer ID"',                    'ACX.SALES_DETAIL_MEMBER_VALUE', 'AMAZON_CUSTOMER_ID',                    'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 2,  '"Royalty Earner"',                        'ACX.SALES_DETAIL_MEMBER_VALUE', 'ROYALTY_EARNER',                        'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 3,  '"Parent Product"',                        'ACX.SALES_DETAIL_MEMBER_VALUE', 'PARENT_PRODUCT',                        'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 4,  '"Author"',                                'ACX.SALES_DETAIL_MEMBER_VALUE', 'AUTHOR',                                'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 5,  '"Title"',                                 'ACX.SALES_DETAIL_MEMBER_VALUE', 'TITLE',                                 'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 6,  '"Digital ISBN"',                          'ACX.SALES_DETAIL_MEMBER_VALUE', 'DIGITAL_ISBN',                          'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 7,  '"Provider Product ID"',                   'ACX.SALES_DETAIL_MEMBER_VALUE', 'PROVIDER_PRODUCT_ID',                   'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 8,  '"Marketplace"',                           'ACX.SALES_DETAIL_MEMBER_VALUE', 'MARKETPLACE',                           'VARCHAR(10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 9,  '"Local Currency"',                        'ACX.SALES_DETAIL_MEMBER_VALUE', 'LOCAL_CURRENCY',                        'VARCHAR(10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 10, '"Membership Type"',                       'ACX.SALES_DETAIL_MEMBER_VALUE', 'MEMBERSHIP_TYPE',                       'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 11, '"Transaction Type"',                      'ACX.SALES_DETAIL_MEMBER_VALUE', 'TRANSACTION_TYPE',                      'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 12, '"Avg Alc Price (in Local Currency)"',     'ACX.SALES_DETAIL_MEMBER_VALUE', 'AVG_ALC_PRICE_LOCAL_CURRENCY',          'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 13, '"Avg Reserve Credits Per Customer"',      'ACX.SALES_DETAIL_MEMBER_VALUE', 'AVG_RESERVE_CREDITS_PER_CUSTOMER',      'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 14, '"Membership Value (in Local Currency)"',  'ACX.SALES_DETAIL_MEMBER_VALUE', 'MEMBERSHIP_VALUE_LOCAL_CURRENCY',       'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 15, '"Reserve Credit Value (in Local Currency)"', 'ACX.SALES_DETAIL_MEMBER_VALUE', 'RESERVE_CREDIT_VALUE_LOCAL_CURRENCY', 'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 16, '"Avg Member Value (in Local Currency)"',  'ACX.SALES_DETAIL_MEMBER_VALUE', 'AVG_MEMBER_VALUE_LOCAL_CURRENCY',       'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 17, '"Effective Avg PWCS"',                    'ACX.SALES_DETAIL_MEMBER_VALUE', 'EFFECTIVE_AVG_PWCS',                    'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 18, '"Member Value per Unit (in Local Currency)"', 'ACX.SALES_DETAIL_MEMBER_VALUE', 'MEMBER_VALUE_PER_UNIT_LOCAL_CURRENCY', 'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 19, '"Royalty Rate"',                          'ACX.SALES_DETAIL_MEMBER_VALUE', 'ROYALTY_RATE',                          'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 20, '"Payee Split"',                           'ACX.SALES_DETAIL_MEMBER_VALUE', 'PAYEE_SPLIT',                           'NUMBER(38,2)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 21, '"FX Rate"',                               'ACX.SALES_DETAIL_MEMBER_VALUE', 'FX_RATE',                               'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 22, '"Earner Currency"',                       'ACX.SALES_DETAIL_MEMBER_VALUE', 'EARNER_CURRENCY',                       'VARCHAR(10)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 23, '"Total Qualified Listens"',               'ACX.SALES_DETAIL_MEMBER_VALUE', 'TOTAL_QUALIFIED_LISTENS',               'NUMBER(38,2)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 24, '"Total Credit Units"',                    'ACX.SALES_DETAIL_MEMBER_VALUE', 'TOTAL_CREDIT_UNITS',                    'NUMBER(38,2)'),
('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 25, '"Net Royalties Earned (in Earner Currency)"', 'ACX.SALES_DETAIL_MEMBER_VALUE', 'NET_ROYALTIES_EARNED_EARNER_CURRENCY', 'NUMBER(38,10)'),

-- ACX_SALES_DETAIL_NET_SALES_STAGE
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 1,  '"Royalty Earner"',          'ACX.SALES_DETAIL_NET_SALES', 'ROYALTY_EARNER',          'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 2,  '"Product ID"',              'ACX.SALES_DETAIL_NET_SALES', 'PRODUCT_ID',              'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 3,  '"Author"',                  'ACX.SALES_DETAIL_NET_SALES', 'AUTHOR',                  'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 4,  '"Title"',                   'ACX.SALES_DETAIL_NET_SALES', 'TITLE',                   'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 5,  '"Digital ISBN"',            'ACX.SALES_DETAIL_NET_SALES', 'DIGITAL_ISBN',            'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 6,  '"Provider Product ID"',     'ACX.SALES_DETAIL_NET_SALES', 'PROVIDER_PRODUCT_ID',     'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 7,  '"Transaction Type"',        'ACX.SALES_DETAIL_NET_SALES', 'TRANSACTION_TYPE',        'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 8,  '"Marketplace"',             'ACX.SALES_DETAIL_NET_SALES', 'MARKETPLACE',             'VARCHAR(10)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 9,  '"Purchase Type"',           'ACX.SALES_DETAIL_NET_SALES', 'PURCHASE_TYPE',           'VARCHAR(100)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 10, '"Offer"',                   'ACX.SALES_DETAIL_NET_SALES', 'OFFER',                   'VARCHAR(50)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 11, '"Royalty Rule"',            'ACX.SALES_DETAIL_NET_SALES', 'ROYALTY_RULE',            'VARCHAR(100)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 12, '"Additional Rule Details"', 'ACX.SALES_DETAIL_NET_SALES', 'ADDITIONAL_RULE_DETAILS', 'VARCHAR(250)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 13, '"Currency"',                'ACX.SALES_DETAIL_NET_SALES', 'CURRENCY',                'VARCHAR(10)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 14, '"Royalty Rate"',            'ACX.SALES_DETAIL_NET_SALES', 'ROYALTY_RATE',            'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 15, '"Payee Split"',             'ACX.SALES_DETAIL_NET_SALES', 'PAYEE_SPLIT',             'NUMBER(38,2)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 16, '"Net Units"',               'ACX.SALES_DETAIL_NET_SALES', 'NET_UNITS',               'NUMBER(38,2)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 17, '"Net Sales"',               'ACX.SALES_DETAIL_NET_SALES', 'NET_SALES',               'NUMBER(38,10)'),
('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 18, '"Net Royalties Earned"',    'ACX.SALES_DETAIL_NET_SALES', 'NET_ROYALTIES_EARNED',    'NUMBER(38,10)'),

-- ACX_SUMMARY_STAGE
('RAW.ACX_SUMMARY_STAGE', 1, '"Royalty Earner"',            'ACX.SUMMARY', 'ROYALTY_EARNER',            'VARCHAR(250)'),
('RAW.ACX_SUMMARY_STAGE', 2, '"Amount Paid (Prior Period)"','ACX.SUMMARY', 'AMOUNT_PAID_PRIOR_PERIOD',  'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 3, '"Balance (Brought Forward)"', 'ACX.SUMMARY', 'BALANCE_BROUGHT_FORWARD',   'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 4, '"Net Royalties Earned"',      'ACX.SUMMARY', 'NET_ROYALTIES_EARNED',      'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 5, '"Adjustments"',               'ACX.SUMMARY', 'ADJUSTMENTS',               'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 6, '"Recoupments"',               'ACX.SUMMARY', 'RECOUPMENTS',               'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 7, '"Net Royalties"',             'ACX.SUMMARY', 'NET_ROYALTIES',             'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 8, '"Bounties"',                  'ACX.SUMMARY', 'BOUNTIES',                  'NUMBER(38,10)'),
('RAW.ACX_SUMMARY_STAGE', 9, '"Payment Due"',               'ACX.SUMMARY', 'PAYMENT_DUE',               'NUMBER(38,10)');
