CREATE TABLE IF NOT EXISTS BOOKS.CONFIG.KENP_RATES (
    MONTH_BEGIN_DATE DATE NOT NULL,
    COUNTRY VARCHAR,
    KENP_RATE FLOAT NOT NULL
);


TRUNCATE TABLE BOOKS.CONFIG.KENP_RATES;

INSERT INTO BOOKS.CONFIG.KENP_RATES
(MONTH_BEGIN_DATE, COUNTRY, KENP_RATE)
VALUES

;