CREATE TABLE IF NOT EXISTS BOOKS.CONFIG.SOURCE_TABLE_INFO (
    RAW_TABLE_NAME   VARCHAR,
    TARGET_TABLE_NAME VARCHAR,
    S3_STAGE_NAME    VARCHAR,
    FILE_FORMAT_NAME VARCHAR,
    COPY_TO_S3_PROC_CALL VARCHAR, 
    MERGE_TO_TARGET_PROC_CALL VARCHAR
);

TRUNCATE TABLE BOOKS.CONFIG.SOURCE_TABLE_INFO;

INSERT INTO BOOKS.CONFIG.SOURCE_TABLE_INFO
VALUES
(
    'RAW.KDP_COMBINED_SALES_STAGE', 'KDP.COMBINED_SALES', 
    'RAW.KDP_COMBINED_SALES_STAGE', 'CONFIG.CSV_SKIP_HEADER_QUOTES', 
    $$CONFIG.COPY_S3_TO_RAW_GENERA(RAW.KDP_COMBINED_SALES_STAGE)$$, 
    $$KDP.MERGE_ORDERS_DATA_BY_ROYALTY_DATE_GENERAL('KDP.COMBINED_SALES')$$
),

(   'RAW.KDP_KENP_STAGE', 'KDP.KENP',           
    'RAW.KDP_KENP_STAGE',  'CONFIG.CSV_SKIP_HEADER_QUOTES', 
    $$CONFIG.COPY_S3_TO_RAW_GENERAL('RAW.KDP_KENP_STAGE')$$, 
    $$KDP.MERGE_ORDERS_DATA_BY_ROYALTY_DATE_GENERAL('KDP.KENP')$$
),

(
    'RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 'ACX.MARKETPLACE_BREAKDOWN_BY_TITLE', 
    'RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE', 'CONFIG.CSV_SKIP_HEADER_QUOTES_SKIP2', 
    $$CONFIG.COPY_S3_TO_RAW_GENERAL('RAW.ACX_MARKETPLACE_BREAKDOWN_BY_TITLE_STAGE')$$, 
    $$$$
),

(
    'RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 'ACX.ROYALTIES_BY_TITLE', 
    'RAW.ACX_ROYALTIES_BY_TITLE_STAGE', 'CONFIG.CSV_SKIP_HEADER_QUOTES_SKIP4', 
    $$CONFIG.COPY_S3_TO_RAW_GENERAL('RAW.ACX_ROYALTIES_BY_TITLE_STAGE')$$, 
    $$$$
),

(
    'RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 'ACX.SALES_DETAIL_MEMBER_VALUE', 
    'RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE', 'CONFIG.CSV_SKIP_HEADER_QUOTES', 
    $$CONFIG.COPY_S3_TO_RAW_GENERAL('RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE')$$, 
    $$$$
),

(
    'RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 'ACX.SALES_DETAIL_NET_SALES', 
    'RAW.ACX_SALES_DETAIL_NET_SALES_STAGE', 'CONFIG.CSV_SKIP_HEADER_QUOTES', 
    $$CONFIG.COPY_S3_TO_RAW_GENERAL('RAW.ACX_SALES_DETAIL_NET_SALES_STAGE')$$, 
    $$$$
),

(
    'RAW.ACX_SUMMARY_STAGE', 'ACX.SUMMARY', 
    'RAW.ACX_SUMMARY_STAGE', 'CONFIG.CSV_SKIP_HEADER_QUOTES', 
    $$CONFIG.COPY_S3_TO_RAW_GENERAL('RAW.ACX_SUMMARY_STAGE')$$, 
    $$$$
)