CREATE TABLE IF NOT EXISTS BIRD.GEO_REGIONS (
    GEO_REGION_SID NUMBER(38,0) DEFAULT BIRD.GEO_REGIONS_SID_SEQ.NEXTVAL,
    GEO_TYPE VARCHAR, 
    GEO_CODE VARCHAR,
    GEO_NAME VARCHAR,
    LOAD_DT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(9)
)