CREATE TABLE IF NOT EXISTS CONNOR.BIRD.TAXONOMY_REFERENCE (
	UNIQUE_KEY NUMBER(38,0),
	SPECIES_CODE VARCHAR(31),
	SPECIES VARCHAR(255),
	SCIENTIFIC_NAME VARCHAR(511),
	SCI_NAME_CODES VARCHAR(63),
	ORDER_NAME VARCHAR(63),
	FAMILY_COMMON_NAME VARCHAR(63),
	FAMILY_SCI_NAME VARCHAR(63),
	FAMILY_CODE VARCHAR(31)
);