CREATE TABLE IF NOT EXISTS BIRD.TAXONOMY_REFERENCE (
	TAXONOMY_REF_SID NUMBER(38,0) DEFAULT BIRD.TAXONOMY_REF_SID_SEQ.NEXTVAL,
	SPECIES_CODE VARCHAR(31),
	SPECIES VARCHAR(255),
	SCIENTIFIC_NAME VARCHAR(511),
	SCI_NAME_CODES ARRAY,
	ORDER_NAME VARCHAR(63),
	FAMILY_COMMON_NAME VARCHAR(63),
	FAMILY_SCI_NAME VARCHAR(63),
	FAMILY_CODE VARCHAR(31),
	LOAD_DT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(9),
	UPDATE_DT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(9)
);