-- Creating PROG USER
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS PROG_USER
PASSWORD = 'XXXXX'; -- CHECK PASSWORD LOCKER FOR PASSWORD

-- Creating Role for PROG USER
CREATE ROLE IF NOT EXISTS PROG_USER_ROLE;
GRANT ROLE PROG_USER_ROLE TO ROLE SYSADMIN;
GRANT ROLE PROG_USER_ROLE TO USER PROG_USER;

-- USE CASE 1: EXECUTE THE LOAD_DAILY_FILES PROC FOR STKZ
USE ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROG_USER_ROLE;
GRANT USAGE ON DATABASE STKZ TO ROLE PROG_USER_ROLE;
GRANT USAGE ON SCHEMA STKZ.STG TO ROLE PROG_USER_ROLE;
GRANT USAGE ON PROCEDURE STKZ.STG.LOAD_DAILY_FILES() TO ROLE PROG_USER_ROLE;

-- USE CASE 1: EXECUTE THE LOAD_COMBINED_SALES_FILES PROC FOR BOOKS
GRANT USAGE ON DATABASE BOOKS TO ROLE PROG_USER_ROLE;
GRANT USAGE ON SCHEMA BOOKS.STG TO ROLE PROG_USER_ROLE;
GRANT USAGE ON PROCEDURE BOOKS.STG.LOAD_COMBINED_SALES_FILES() TO ROLE PROG_USER_ROLE;


SHOW GRANTS TO ROLE PROG_USER_ROLE;


-- EDIT to PROG_USER: set up for Key-Pair auth
ALTER USER PROG_USER SET TYPE='SERVICE';
ALTER USER PROG_USER SET RSA_PUBLIC_KEY = '<key ommitted for repository push. see ~/source/rsa_keys/ or AWS secrets manager';