CREATE OR REPLACE NOTIFICATION INTEGRATION BASIC_EMAIL_INTEGRATION
  TYPE = EMAIL
  ENABLED=TRUE
  ALLOWED_RECIPIENTS=('connorruff99@gmail.com')
;


GRANT USAGE ON INTEGRATION BASIC_EMAIL_INTEGRATION TO ROLE ZETA_BALL_ADMIN;