CREATE TABLE IF NOT EXISTS IDEA.CORE.BLURBS (
	BLURB_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	EPISODE_ID NUMBER(38,0),
	SERIES_ID NUMBER(38,0),
	BLURB_TEXT VARCHAR(500),
	OCCURS_AT_SECOND NUMBER(38,0),
	LIKES NUMBER(38,0),
	PARENT_BLURB_ID NUMBER(38,0),
	SUPER_PARENT_BLURB_ID NUMBER(38,0),
	NUM_CHILDREN NUMBER(38,0)
);