CREATE TABLE IF NOT EXISTS IDEA.CORE.EPISODES (
	EPOSIDE_ID NUMBER(38,0),
	SERIES_ID NUMBER(38,0),
	EPSIODE_NAME VARCHAR(200),
	SEASON_NUMBER NUMBER(38,0),
	EPISODE_IN_SEASON NUMBER(38,0),
	EPISODE_IN_SERIES NUMBER(38,0),
	DURATION_SECONDS NUMBER(38,0)
);