CREATE PROCEDURE IF NOT EXISTS BOOKS.STG.LOAD_COMBINED_SALES_FILES()
RETURNS VARCHAR 
LANGUAGE SQL 
EXECUTE AS OWNER 
AS 
$$
DECLARE 
    AUDIT_SID_VAR INT;
BEGIN     


    TRUNCATE TABLE STG.COMBINED_SALES;

    COPY INTO STG.COMBINED_SALES
    FROM (
        SELECT 
            $1, $2, $3, $4, $5, 
            $6, $7, $8, $9, $10, 
            $11, $12, $13, $14, $15,
            METADATA$FILENAME,
            CURRENT_TIMESTAMP()
        FROM @STG.COMBINED_SALES_STAGE
        (FILE_FORMAT => 'STG.CSV_SKIP_HEADER_QUOTES')
    );

    DELETE FROM DATA.COMBINED_SALES 
    WHERE ROYALTY_DATE IN (
        SELECT ROYALTY_DATE 
        FROM STG.COMBINED_SALES
    );

    INSERT INTO DATA.COMBINED_SALES
    SELECT * FROM STG.COMBINED_SALES;


    RETURN 'SUCCESS';

END
$$
;