USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS BAR_GUYD;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS BAR_GUYD_ADMIN;
GRANT ROLE BAR_GUYD_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
SHOW GRANTS ON ROLE BAR_GUYD_ADMIN;
SHOW GRANTS TO ROLE BAR_GUYD_ADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BAR_GUYD_ADMIN;
GRANT USAGE ON DATABASE BAR_GUYD TO ROLE BAR_GUYD_ADMIN;
GRANT CREATE SCHEMA ON DATABASE BAR_GUYD TO ROLE BAR_GUYD_ADMIN;

USE ROLE BAR_GUYD_ADMIN;
USE DATABASE BAR_GUYD;
CREATE SCHEMA IF NOT EXISTS DWH;


SHOW GRANTS ON SCHEMA BAR_GUYD.DWH;


USE ROLE ACCOUNTADMIN;

GRANT USAGE ON INTEGRATION S3_FULL_INT TO ROLE BAR_GUYD_ADMIN;

USE ROLE BAR_GUYD_ADMIN;
USE SCHEMA BAR_GUYD.DWH;
USE WAREHOUSE COMPUTE_WH;


