USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS BOOKS;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS BOOKS_ADMIN;
GRANT ROLE BOOKS_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
SHOW GRANTS ON ROLE BOOKS_ADMIN;
SHOW GRANTS TO ROLE BOOKS_ADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BOOKS_ADMIN;
GRANT USAGE ON DATABASE BOOKS TO ROLE BOOKS_ADMIN;
GRANT CREATE SCHEMA ON DATABASE BOOKS TO ROLE BOOKS_ADMIN;

USE ROLE BOOKS_ADMIN;
USE DATABASE BOOKS;
CREATE SCHEMA IF NOT EXISTS STG;


SHOW GRANTS ON SCHEMA BOOKS.STG;


USE ROLE ACCOUNTADMIN;

GRANT USAGE ON INTEGRATION S3_FULL_INT TO ROLE BOOKS_ADMIN;

USE ROLE BOOKS_ADMIN;

CREATE SCHEMA IF NOT EXISTS BOOKS.DATA;
