USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS CONNOR;
GRANT USAGE ON DATABASE CONNOR TO ROLE CONNOR_ADMIN;
CREATE SCHEMA CONNOR.STG;

GRANT OWNERSHIP ON SCHEMA CONNOR.STG TO ROLE CONNOR_ADMIN;

USE ROLE CONNOR_ADMIN;