USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS STKZ;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS STKZ_ADMIN;

GRANT ROLE STKZ_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

SHOW GRANTS ON ROLE STKZ_ADMIN;
SHOW GRANTS TO ROLE STKZ_ADMIN;

USE ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE STKZ_ADMIN;
GRANT USAGE ON DATABASE STKZ TO ROLE STKZ_ADMIN;
SHOW GRANTS ON DATABASE STKZ;
GRANT CREATE SCHEMA ON DATABASE STKZ TO ROLE STKZ_ADMIN;

USE ROLE STKZ_ADMIN;
CREATE SCHEMA IF NOT EXISTS STG;

SHOW GRANTS ON SCHEMA STKZ.STG;

CREATE SCHEMA IF NOT EXISTS MOOLA;