USE ROLE SYSADMIN;
CREATE DATABASE TERR;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS TERR_ADMIN;
GRANT ROLE TERR_ADMIN TO ROLE SYSADMIN;


USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS TERR_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE 
;

GRANT USAGE ON WAREHOUSE TERR_WH TO ROLE TERR_ADMIN;
GRANT USAGE ON DATABASE TERR TO ROLE TERR_ADMIN;
GRANT CREATE SCHEMA ON DATABASE TERR TO ROLE TERR_ADMIN;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE TERR TO ROLE TERR_ADMIN;

USE ROLE TERR_ADMIN;


CREATE SCHEMA TERR.DBO;
CREATE SCHEMA TERR.CONFIG;
CREATE SCHEMA TERR.STG;
