USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS ZETA_BALL;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS ZETA_BALL_ADMIN;
GRANT ROLE ZETA_BALL_ADMIN TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
SHOW GRANTS ON ROLE ZETA_BALL_ADMIN;
SHOW GRANTS TO ROLE ZETA_BALL_ADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ZETA_BALL_ADMIN;
GRANT USAGE ON DATABASE ZETA_BALL TO ROLE ZETA_BALL_ADMIN;
GRANT CREATE SCHEMA ON DATABASE ZETA_BALL TO ROLE ZETA_BALL_ADMIN;

USE ROLE ZETA_BALL_ADMIN;
USE DATABASE ZETA_BALL;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS STG;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA ZETA_BALL.DWH TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA ZETA_BALL.STG TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA ZETA_BALL.DWH TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA ZETA_BALL.STG TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA ZETA_BALL.DWH TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA ZETA_BALL.STG TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA ZETA_BALL.DWH TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA ZETA_BALL.STG TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA ZETA_BALL.STG TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA ZETA_BALL.DWH TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA ZETA_BALL.STG TO ROLE ZETA_BALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA ZETA_BALL.DWH TO ROLE ZETA_BALL_ADMIN;

SHOW GRANTS ON SCHEMA ZETA_BALL.DWH;


USE ROLE ACCOUNTADMIN;

GRANT USAGE ON INTEGRATION S3_FULL_INT TO ROLE ZETA_BALL_ADMIN;

USE ROLE ZETA_BALL_ADMIN;
USE SCHEMA ZETA_BALL.DWH;
USE WAREHOUSE COMPUTE_WH;



