CREATE OR REPLACE TABLE BOOKS.RAW.ACX_SALES_DETAIL_NET_SALES_STAGE (
    "Royalty Earner"          VARCHAR,
    "Product ID"              VARCHAR,
    "Author"                  VARCHAR,
    "Title"                   VARCHAR,
    "Digital ISBN"            VARCHAR,
    "Provider Product ID"     VARCHAR,
    "Transaction Type"        VARCHAR,
    "Marketplace"             VARCHAR,
    "Purchase Type"           VARCHAR,
    "Offer"                   VARCHAR,
    "Royalty Rule"            VARCHAR,
    "Additional Rule Details" VARCHAR,
    "Currency"                VARCHAR,
    "Royalty Rate"            VARCHAR,
    "Payee Split"             VARCHAR,
    "Net Units"               VARCHAR,
    "Net Sales"               VARCHAR,
    "Net Royalties Earned"    VARCHAR,
    DP_RUN_ID               VARCHAR,
    DP_SOURCE_FILE_NAME     VARCHAR,
    DP_SOURCE_FILE_ROW_NUMBER INT,
    DP_LOAD_TIMESTAMP       TIMESTAMP_NTZ(9)
);
