CREATE OR REPLACE TABLE BOOKS.RAW.ACX_ROYALTIES_BY_TITLE_STAGE (
    "Royalty Earner"                                VARCHAR,
    "Product ID"                                    VARCHAR,
    "Author"                                        VARCHAR,
    "Title"                                         VARCHAR,
    "Digital ISBN"                                  VARCHAR,
    "Member Credit Sales and TQLs - Net Units"      VARCHAR,
    "Member Credit Sales and TQLs - TQLs"           VARCHAR,
    "Member Credit Sales and TQLs - Net Royalties"  VARCHAR,
    "Member Credit Sales AL - Net Units"            VARCHAR,
    "Member Credit Sales AL - Net Royalties"        VARCHAR,
    "Member Cash Sales ALOP - Net Units"            VARCHAR,
    "Member Cash Sales ALOP - Net Royalties"        VARCHAR,
    "Non-Member Cash Sales ALC - Net Units"         VARCHAR,
    "Non-Member Cash Sales ALC - Net Royalties"     VARCHAR,
    "On-Demand - Listening Minutes"                 VARCHAR,
    "On-Demand - Net Royalties"                     VARCHAR,
    "Total - Net Units"                             VARCHAR,
    "Total - TQLs"                                  VARCHAR,
    "Total - Listening Minutes"                     VARCHAR,
    "Total - Net Royalties Earned"                  VARCHAR,
    "Total - Adjustments"                           VARCHAR,
    "Total - Recoupments"                           VARCHAR,
    "Total - Net Royalties"                         VARCHAR,
    DP_RUN_ID               VARCHAR,
    DP_SOURCE_FILE_NAME     VARCHAR,
    DP_SOURCE_FILE_ROW_NUMBER INT,
    DP_LOAD_TIMESTAMP       TIMESTAMP_NTZ(9)
);
