CREATE OR REPLACE TABLE BOOKS.RAW.ACX_SALES_DETAIL_MEMBER_VALUE_STAGE (
    "Amazon Customer ID"                        VARCHAR,
    "Royalty Earner"                            VARCHAR,
    "Parent Product"                            VARCHAR,
    "Author"                                    VARCHAR,
    "Title"                                     VARCHAR,
    "Digital ISBN"                              VARCHAR,
    "Provider Product ID"                       VARCHAR,
    "Marketplace"                               VARCHAR,
    "Local Currency"                            VARCHAR,
    "Membership Type"                           VARCHAR,
    "Transaction Type"                          VARCHAR,
    "Avg Alc Price (in Local Currency)"         VARCHAR,
    "Avg Reserve Credits Per Customer"          VARCHAR,
    "Membership Value (in Local Currency)"      VARCHAR,
    "Reserve Credit Value (in Local Currency)"  VARCHAR,
    "Avg Member Value (in Local Currency)"      VARCHAR,
    "Effective Avg PWCS"                        VARCHAR,
    "Member Value per Unit (in Local Currency)" VARCHAR,
    "Royalty Rate"                              VARCHAR,
    "Payee Split"                               VARCHAR,
    "FX Rate"                                   VARCHAR,
    "Earner Currency"                           VARCHAR,
    "Total Qualified Listens"                   VARCHAR,
    "Total Credit Units"                        VARCHAR,
    "Net Royalties Earned (in Earner Currency)" VARCHAR,
    DP_RUN_ID               VARCHAR,
    DP_SOURCE_FILE_NAME     VARCHAR,
    DP_SOURCE_FILE_ROW_NUMBER INT,
    DP_LOAD_TIMESTAMP       TIMESTAMP_NTZ(9)
);
